name: Prepare Release PR

on:
  workflow_run:
    workflows: ["Test Build and Publish Alpha"]
    types:
      - completed
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create or Update PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if PR already exists
          existing_pr=$(gh pr list --base publish --head main --json number -q '.[0].number')
          
          if [ ! -z "$existing_pr" ]; then
            echo "Closing existing PR #$existing_pr"
            gh pr close $existing_pr
          fi
          
          # Create new PR
          gh pr create \
            --base publish \
            --head main \
            --title "[AUTO] Prepare to release" \
            --body "Automated PR to prepare for release"