name: Publish Release

on:
  push:
    branches:
      - publish

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node env 🏗
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"
          cache: 'npm'

      - name: Add npm registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test

      - name: Build packages
        run: |
          npm run build
          echo "Finished running build"

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH }}
        run: npx semantic-release

      - name: cleanup
        if: always()
        run: if [ -e .npmrc ]; then rm .npmrc; fi